# IceMaze (c) 2012-2013 by Matt Cudmore

examples = {
	"gs0" : [
		"The original Ice Path"
		"EA4PDQ8HQEBAQEBAQEBAQEBAQEBAAAAAAEAAAAAAAAAAQEAAAABAAAAAAAAAAABAQAAAAAAAAABAAAAAAEBAAEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAABAAEBAAAAAAAAAQAAAAAAAQEAAAAAAAAAAAABAAABAQEAAAABAAAAAAAAAAEBAAABAAAAAAAAAAEAAQEAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAQEAAAAAAAEAAAEAAAAAgQEBAQEBAQCAgQEBAQCA="
	]
}

loadExample = (id) ->
	if eg = examples[id] then alert "Example: #{eg[0]}"
	else return alert "Example[#{id}] is undefined"
	loadMaze decodeMaze eg[1]
